### ISSUE TITLE
Auto reconnect after a shutdown

### ISSUE THREAD

**Issue by licaon-kter** [dino/dino#581]
Dino HEAD, Linux

Steps:
1. be connected
2. stop server
3. start server

Expected result:
After (re)start Dino would reconnect.

Actual result:
Dino stuck with "system shutdown", fix it by toggling account off then on.

**Comment by catap** [comment]
I'd like to confirm that I see similar issue in 0.5.0 and it includes the case when router is rebooted or soemthing bad had happened with internet connection.

**Comment by aehimself** [comment]
The issue is going to be more complex. I personally never seen this happen even if I restart eJabberD or the OS running it, neither when my public IP address changes. Mostly using Dino 0.4.5, 0.5.0 on Windows and Linux platforms plus Conversations on the phone.

I'm running eJabberD 21.12-1 on an Ubuntu server 22.04.5 LTS. Machine is behind NAT with STUN and TURN (ejabberd_stun) and SOCKS5 (mod_proxy65). DNS records are set up.

Do we know the config of the server producing the issue?

**Comment by catap** [comment]
@aehimself I run dino on Laptop and I had reproduced it on my home network. Home network is:
1. multiple WANs with IPv4 NAT;
2. intervanl IPv6 which "maps" into external IPv6.

WAN works in failover mode, so, if the first one is down, it switched to the second, if second is down to the third.

This mean that socket can be broken at any time.

A bit redacted ejabberd config:

```
listen:
  -
    port: 5222
    ip: "0.0.0.0"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 262144
    shaper: c2s_shaper
    access: c2s
    starttls_required: true
  -
    port: 5269
    ip: "0.0.0.0"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
    shaper: s2s_shaper
  -
    port: 5269
    ip: "::"
    module: ejabberd_s2s_in
    max_stanza_size: 524288
    shaper: s2s_shaper
  -
    port: 5280
    ip: "127.0.0.1"
    module: ejabberd_http
    request_handlers:
      /xmpp/bosh: mod_bosh
      /xmpp/ws: ejabberd_http_ws
      /xmpp/upload: mod_http_upload
  -
    port: 8448
    ip: "0.0.0.0"
    module: ejabberd_http
    tls: true
    request_handlers:
      "/_matrix": mod_matrix_gw
  -
    port: 8448
    ip: "::"
    module: ejabberd_http
    tls: true
    request_handlers:
      "/_matrix": mod_matrix_gw
  -
    port: 5478
    ip: "0.0.0.0"
    transport: udp
    module: ejabberd_stun
    use_turn: true
  -
    port: 5478
    ip: "::"
    transport: udp
    module: ejabberd_stun
    use_turn: true

...
modules:
  mod_adhoc: {}
  mod_announce:
    access: announce
  mod_avatar: {}
  mod_blocking: {}
  mod_bosh: {}
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {}
  mod_disco:
    server_info:
      -
        modules: all
        name: "abuse-addresses"
        urls: ["mailto:abuse@@HOST@"]
  mod_fail2ban: {}
  mod_http_upload:
    put_url: https://upload-mx0.@HOST@/xmpp/upload
    custom_headers:
      "Access-Control-Allow-Origin": "https://upload-mx0.@HOST@"
      "Access-Control-Allow-Methods": "GET,HEAD,PUT,OPTIONS"
      "Access-Control-Allow-Headers": "Content-Type"
    max_size: infinity
  mod_http_upload_quota: {}
  mod_jidprep: {}
  mod_last: {}
  mod_matrix_gw:
    key_name: "XXX"
    key: "YYY"
  mod_mam:
    assume_mam_usage: true
    default: always
  mod_offline:
    access_max_user_messages: max_user_offline_messages
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_proxy65:
    access: local
    max_connections: 5
  mod_pubsub:
    access_createnode: pubsub_createnode
    plugins:
      - flat
      - pep
    force_node_config:
      ## Avoid buggy clients to make their bookmarks public
      storage:bookmarks:
        access_model: whitelist
  mod_push: {}
  mod_push_keepalive: {}
  mod_register:
    ip_access: trusted_network
  mod_roster:
    versioning: true
  mod_s2s_bidi: {}
  mod_s2s_dialback: {}
  mod_shared_roster: {}
  mod_stream_mgmt:
    resend_on_timeout: if_offline
  mod_stun_disco: {}
  mod_vcard: {}
  mod_vcard_xupdate: {}
  mod_version:
    show_os: false
```
